language: node_js
cache:
  directories:
  - node_modules
node_js:
  - "6"
group: bluezone
install: npm install
script: npm run build && npm test

deploy:
  provider: script
  script: sh travis.ci/deploy.sh
  on:
    all_branches: true
